name: simple
description: simple pipeline

triggers:
  - cron: "* * * * *"
  - webhook: "/webhooks/example"

tasks:
  -
    name: task1
    command: "echo 'task1 executed'"
    result_check: "echo 'check task1 result'"
  -
    name: task2
    command: "exit 1"
    depends_on:
      - task1
  -
    name: task3
    command: "echo 'task3 executed'"
    depends_on:
      - task2
